### ISSUE TITLE
objectClass of CurrentPerformace and HistoricalPerformance data type is not needed

### ISSUE THREAD

**Issue by niloda** [openBackhaul/hybridMwStructure#18]
see description provided for airInterface model

**Comment by demx8as6** [comment]
Based on the fact that 1+1 protection implementation by one vendor requires the implementation of alarms, PM and its configuration, this issue should be closed without any change on the model. 
As a consequence the vendors should implement the default values stating that the related implementation is not supported.

**Comment by openBackhaul** [comment]
No change required to the modeling. Issue => closed
