### ISSUE TITLE
Object References in CurrentPerformance to be deleted

### ISSUE THREAD

**Issue by openBackhaul** [openBackhaul/hybridMwStructure#19]
CurrentPerformance::objectClass, nameBinding, packages and allomorphs to be removed from the model.

**Comment by demx8as6** [comment]
Based on the fact that 1+1 protection implementation by one vendor requires the implementation of alarms, PM and its configuration, this issue should be closed without any change on the model. 
As a consequence the vendors should implement the default values stating that the related implementation is not supported.

**Comment by demx8as6** [comment]
Decision 2020-11-11: to be deleted as proposed.

**Comment by openBackhaul** [comment]
UML and YANG to the update.
Issue to be kept open until then.

**Comment by openBackhaul** [comment]
**Decision made at the 5G-xhaul call on 7th of July:**
UML and YANG are already corrected.
Existing implementations are basing on the corrected YANG.
Same procedure as with https://github.com/openBackhaul/airInterface/issues/27: Just closing the issue
