### ISSUE TITLE
TdmStructureKind is missing in HybridMWStractureCapability and HybridMWStractureConfiguration UML diagram

### ISSUE THREAD

**Issue by krgaurav29** [openBackhaul/hybridMwStructure#21]
TdmStructureKind is present in hybrid-mw-structure-configuration yang file as a string but is complex type in UML.
'supported-tdm-structure-kind-list' is present instead of 'tdm-structure-kind' in hybrid-mw-structure-capability Yang file.

**Comment by openBackhaul** [comment]
The attribute is represented as an arrow.
There can't be anything corrected in the UML diagram.
UML and YANG files are anyway correct.
Issue gets immediately closed.
