### ISSUE TITLE
Deleting alarm attributes from the modeling

### ISSUE THREAD

**Issue by openBackhaul** [openBackhaul/hybridMwStructure#22]
Latest testing showed that none of the devices under test is supporting alarms in the PureEthernetStructure and the HybridMwStructure.

Vendors not participating in the tests also confirmed that their devices don't implement alarms on these interfaces.

Proposal:
It should be considered to remove:
- HybridMwStructureCapability::supportedAlarmList attribute
- HybridMwStructureConfiguration::problemKindSeverityList attribute incl. ProblemKindSeverityType datatype and SeverityType enumeration
- HybridMwStructureConfiguration::g826ThresholdCrossAlarmList attribute incl. G826ThresholdCrossAlarmType datatype and G826Type enumeration
- HybridMwStructureConfiguration::clearingThresholdCrossAlarmsIsOn attribute
- HybridMwStructureCurrentProblems class incl. HybridMwStructureCurrentProblemType datatype and CurrentProblem class

**Comment by openBackhaul** [comment]
Decision at the 5G-xhaul call on Tuesday 2nd of September 2020:

The following elements shall be removed:
- HybridMwStructureCapability::supportedAlarmList attribute
- HybridMwStructureConfiguration::problemKindSeverityList attribute incl. ProblemKindSeverityType datatype and SeverityType enumeration
- HybridMwStructureConfiguration::g826ThresholdCrossAlarmList attribute incl. G826ThresholdCrossAlarmType datatype and G826Type enumeration
- HybridMwStructureConfiguration::clearingThresholdCrossAlarmsIsOn attribute
- HybridMwStructureCurrentProblems class incl. HybridMwStructureCurrentProblemType datatype and CurrentProblem class

Updating UML and YANG required.

**Comment by demx8as6** [comment]
Based on the fact that 1+1 protection implementation by one vendor requires the implementation of alarms, PM and its configuration, the decision from Sep2 2020 is reverted.
As a consequence the vendors should implement the default values stating that the related implementation is not supported.

**Comment by openBackhaul** [comment]
No change required at the modeling. Issue => closed
