### ISSUE TITLE
leafref changes for path and must statement to point the same LTP instance.

### ISSUE THREAD

**Issue by PrathibaJee** [openBackhaul/hybridMwStructure#25]
**Problem:**
For the attribute tdm-structure-kind in hybrid-mw-structure-configuration , pyang tool reports warning with regards to the must statements defined , 

> hybrid-mw-structure-2-0.yang:440: warning: node "hybrid-mw-structure-2-0::hybrid-mw-structure-capability" is config false and is not part of the accessible tree

the current "must" statement for the attribute is not pointing to the capabilities of the same LTP instance.

**Possible solution :**

```
leaf tdm-structure-kind {
                type leafref {
                    path "/core-model:control-construct/core-model:logical-termination-point[core-model:uuid = current()/../../../../core-model:uuid]/core-model:layer-protocol[core-model:local-id = current()/../../../core-model:local-id]/hybrid-mw-structure:hybrid-mw-structure-pac/hybrid-mw-structure:hybrid-mw-structure-capability/hybrid-mw-structure:supported-tdm-structure-kind-list/hybrid-mw-structure:tdm-structure-name";
                    require-instance false;
                }
                must  'deref(.) = current()';
                description    
                    "TDM frame to be applied.";
            }
```

**Comment by openBackhaul** [comment]
Fixed with HybridMwStructure_2.0.0-tsp.220315.1810.
